name: Build and publish a Docker image to ghcr.io

on:
  # publish on releases, e.g. v2.1.13 (image tagged as "2.1.13" - "v" prefix is removed)
  release:
    types: [ published ]

  # publish on pushes to the main branch (image tagged as "latest")
  push:
    branches:
      - main

jobs:
  docker_publish:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2

      # Build and publish Docker image
      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          image_name: ${{ github.repository }}  # it will be lowercased internally
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Optional: Update Docker Hub as well
      # - name: Build and publish to Docker Hub
      #   uses: macbre/push-to-ghcr@master
      #   with:
      #     image_name: ${{ github.repository }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     docker_io_token: ${{ secrets.DOCKER_IO_ACCESS_TOKEN }}
      #     repository: docker.io